#!/usr/bin/env python3
"""Batch 3 — LLM Fine-tuning: datasets and synthetic data (8 sources)."""
import re, datetime
from pathlib import Path
V = Path("/Users/hamidadesokan/Documents/Knowledge Management/LLM Fine-tuning")
TODAY = "2026-08-30"
NOW = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

RAW = {
 "uns":  "doc-datasets-guide-unsloth-documentation.md",
 "cos":  "blog-cosmopedia-how-to-create-large-scale-synthetic-data-for-pre-training-large-langu.md",
 "rest": "pdf-231206585-beyond-human-data-scaling-self-training-for-problem-solving-with-langu.md",
 "cur":  "code-github-bespokelabsaicurator-synthetic-data-curation-for-post-training-and-struct.md",
 "dis":  "doc-distilabel-docs.md",
 "nom":  "blog-data-exploration-and-filtering-with-nomic-atlas.md",
 "easy": "blog-paper-page-easy-dataset-a-unified-and-extensible-framework-for-synthesizing-llm-.md",
 "dav":  "code-github-davanstriendata-for-fine-tuning-llms-github.md",
}
TITLE = {
 "uns":"Datasets Guide - Unsloth Documentation",
 "cos":"Cosmopedia: how to create large-scale synthetic data for pre-training Large Language Models",
 "rest":"Beyond Human Data: Scaling Self-Training for Problem-Solving with Language Models",
 "cur":"bespokelabsai/curator - Synthetic data curation for post-training",
 "dis":"Distilabel Docs",
 "nom":"Data exploration and filtering with Nomic Atlas",
 "easy":"Easy Dataset: A Unified and Extensible Framework for Synthesizing LLM Fine-Tuning Data",
 "dav":"davanstrien/data-for-fine-tuning-llms",
}
def y(v):
    if not re.search(r'[:#\[\]{}&*!|>%@`\'"]|^\s|\s$|^$', v): return v
    return '"'+v.replace("\\","\\\\")+'"' if '"' not in v else "'"+v.replace("'","''")+"'"
def page(path, ftype, title, desc, tags, keys, body, depth):
    up="../"*depth
    src="sources:\n"+"".join(f"  - id: {RAW[k][:-3][:38]}\n    resource: {up}Raw/{RAW[k]}\n    title: \"{TITLE[k]}\"\n" for k in keys)
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(f"---\ntype: {ftype}\ntitle: {y(title)}\ntags: [{', '.join(tags)}]\n{src}"
                    f"updated: {TODAY}\ndescription: {y(desc)}\n"
                    f'generated: {{ by: "agent:claude-opus-5", at: "{NOW}" }}\n---\n\n{body.strip()}\n',encoding="utf-8")
S,C,P = V/"Wiki"/"summaries", V/"Wiki"/"concepts", V/"Wiki"/"papers"

page(S/"unsloth-datasets-guide.md","summary","Unsloth Datasets Guide",
 "what to decide before formatting data, and the chat-template formats a tokenizer can read",
 ["llm-finetuning","datasets","chat-template"],["uns"],"""
# Unsloth Datasets Guide

Practical guidance on preparing data for fine-tuning. Its framing: text has to be in a
format a tokenizer can read, and **the chat template and how you design it is one of the
key parts of creating a dataset**.

## Decide three things first

The guide says to identify these before formatting anything:

- **Purpose** — what the data is for, which determines what you need and which format to
  use. Its examples are chat-based dialogue (Q&A, language learning, customer support) and
  domain-specific data (medical, finance, technical).
- **Style of output** — JSON, HTML, text or code; or a target language.
- **Data source** — once purpose and style are known, analyse quality and quantity. It
  points at Hugging Face and Wikipedia, noting Wikipedia is especially useful for teaching
  a model a language.

## Formats

- **Alpaca-style instruction format** for adapting a model to a task where it should
  produce single-turn output from a specific set of instructions.
- **ChatML**, described as the other common format and the Hugging Face default.
- **ShareGPT** data uses `from`/`value` keys rather than ChatML's `role`/`content`;
  `standardize_sharegpt` converts it.

One quality suggestion worth carrying: combining your dataset with a more generalized one
such as ShareGPT, which the guide says makes the model smarter and more diverse.

Related: [Synthetic Data](../concepts/Synthetic%20Data.md).
""",2)

page(S/"cosmopedia-synthetic-pretraining-data.md","summary","Cosmopedia (Hugging Face)",
 "scaling synthetic generation to 25B tokens, where the real work was prompt curation for diversity",
 ["llm-finetuning","synthetic-data","datasets"],["cos"],"""
# Cosmopedia

Hugging Face's attempt to reproduce the training data behind Phi-1.5, and — unusually —
to release all of it: pipeline code, dataset, and a 1B model (`cosmo-1b`) trained on it.

## What it is

Synthetic textbooks, blog posts, stories, posts and WikiHow articles generated by
**Mixtral-8x7B-Instruct-v0.1**. Over **30 million files and 25 billion tokens**, described
in the post as the largest open synthetic dataset to date.

The scope is deliberately different from most synthetic-data writing: not
instruction-tuning sets of a few thousand samples, but **millions of samples for
pre-training LLMs from scratch**, which the post says presents its own challenges.

## Why it exists

Microsoft's Phi models were predominantly trained on synthetic data and surpassed larger
models trained longer on web data. But the technical reports **leave out substantial
detail about how the synthetic training data was curated, and the datasets are not
released**. The post is candid that this fuels a genuine dispute — some praise the
results, critics argue the models may simply be overfitting benchmarks, and some label
pretraining on synthetic data "garbage in, garbage out".

## The finding worth keeping

> most of the time for Cosmopedia was spent on meticulous prompt engineering

Not GPU orchestration. **Diversity is the hard part**: at scale you must curate prompts
covering many topics and minimize duplicate outputs, or you spend compute generating
billions of near-identical textbooks and discard most. Over 30 million prompts spanning
hundreds of topics achieved **less than 1% duplicate content**.

For reference, the Phi-1.5 technical report describes curating 20,000 topics to seed 20
billion tokens, using web samples for diversity — but the post notes the methodology for
combining topics and web samples remains unclear.

Related: [Synthetic Data](../concepts/Synthetic%20Data.md).
""",2)

page(S/"rest-em-beyond-human-data.md","summary","Beyond Human Data / ReST-EM (Google DeepMind)",
 "self-training on model-generated data filtered by binary feedback, beating fine-tuning on human data",
 ["llm-finetuning","synthetic-data","self-training"],["rest"],"""
# Beyond Human Data / ReST-EM

Singh, Co-Reyes, Agarwal et al., Google DeepMind and Mila. The question: can fine-tuning
go beyond human-generated data on tasks **where scalar feedback is available** — for
example maths problems, where correctness can be verified?

## The method

A simple self-training method based on expectation-maximization, called **ReST-EM**:

1. Generate samples from the model and **filter them using binary feedback**.
2. Fine-tune the model on the surviving samples.
3. Repeat a few times.

The paper positions this as a modification of Reinforced Self-Training (ReST, Gulcehre et
al.) and shows it can be viewed as applying expectation-maximization for reinforcement
learning.

## Results

Tested on advanced **MATH** reasoning and **APPS** coding benchmarks with PaLM-2 models,
ReST-EM **scales favourably with model size and significantly surpasses fine-tuning only
on human data**.

The stated conclusion is bounded and worth quoting in shape: the findings *suggest*
self-training with feedback can reduce dependence on human-generated data. The premise it
rests on — access to scalar or binary feedback — is what limits where this transfers.

Paper page: [Beyond Human Data](../papers/Beyond%20Human%20Data.md).
Related: [Synthetic Data](../concepts/Synthetic%20Data.md).
""",2)

page(S/"synthetic-data-tooling.md","summary","Synthetic-data tooling: Curator, Distilabel, Easy Dataset",
 "three frameworks for generating and curating fine-tuning data, and what each optimizes for",
 ["llm-finetuning","synthetic-data","tooling"],["cur","dis","easy"],"""
# Synthetic-data tooling

Three tools in this corpus generate or curate fine-tuning data. They differ in what they
assume you already have.

## Bespoke Curator

Positioned as **synthetic data curation for post-training and structured data
extraction**. Its changelog shows the direction of travel — from curation into training:

- Tinker integration (2026.03.14): curated data to a LoRA fine-tuned model in a few lines.
- Fireworks AI integration (2026.06.09): managed SFT with `FireworksTrainer` — upload
  curated data, train a LoRA, sample from the deployed model behind the same interface.
- Used to create **OpenThoughts2-1M**, which trained OpenThinker2-32B, reported as
  outperforming DeepSeek-R1-32B.

## Distilabel (Argilla)

An **AI Feedback (AIF) framework** for building datasets with and for LLMs — synthetic
data plus feedback, aimed at engineers wanting fast, reliable, scalable pipelines
**based on verified research papers**. The emphasis is on pipelines that reproduce known
methods rather than ad-hoc generation.

## Easy Dataset

A framework for synthesizing fine-tuning data **from unstructured documents**, through a
GUI. Its pipeline: configure text extraction and chunking to turn raw documents into
coherent chunks, then use **persona-driven prompting** to generate diverse question-answer
pairs with publicly available LLMs, with a **human-in-the-loop visual interface** for
reviewing intermediate outputs.

Its evaluation is on a **financial question-answering task**, where fine-tuning on the
synthesized dataset is reported to significantly improve domain-specific performance
**while preserving general knowledge**. The paper page notes over 9,000 GitHub stars.

The gap it targets is stated plainly: adapting LLMs to specific domains is limited by
scarce high-quality domain data, and existing synthesis tools struggle to extract reliable
fine-tuning data from heterogeneous documents.

Paper page: [Easy Dataset](../papers/Easy%20Dataset.md).
Related: [Synthetic Data](../concepts/Synthetic%20Data.md).
""",2)

page(S/"data-exploration-and-deduplication.md","summary","Data exploration and deduplication",
 "finding duplicates and bad records before training, with Nomic Atlas and a conference-session notebook set",
 ["llm-finetuning","datasets","data-quality"],["nom","dav"],"""
# Data exploration and deduplication

Two sources on the unglamorous half of dataset work: looking at the data before training
on it.

## Nomic Atlas (Alexander Visheratin)

The scenario: you want to fine-tune a VLM on brand-new data, so the **first thing needed
is to analyse the data and find possible issues — incorrect data, duplicates**. Doing that
requires going through the data both manually and programmatically.

The post's honest argument for using a platform rather than rolling your own: the author
says from experience that **building such tooling from scratch is hard and very
time-consuming**. It demonstrates visualizing a multimodal dataset, combining multiple
projections onto one map, and **detecting duplicates across multiple fields** such as
images and questions.

## davanstrien/data-for-fine-tuning-llms

Notebooks accompanying a session at the Mastering LLMs conference, covering *some* of the
data issues in fine-tuning. Their stated goal is the balance that defines dataset work:

> sufficiently diverse data, with high quality and the right quantity i.e. avoid duplication

The repository's first notebook is EDA and deduplication, which is the same starting point
as the Atlas post reaches by a different route.

Related: [Synthetic Data](../concepts/Synthetic%20Data.md).
""",2)

# ---- concept ----
page(C/"Synthetic Data.md","concept","Synthetic Data",
 "model-generated training data: why it is used, where it demonstrably works, and what makes it hard",
 ["llm-finetuning","synthetic-data","datasets"],["cos","rest","easy","cur","dis"],"""
# Synthetic Data

Training data generated by a model rather than collected from people.

## Why

The traditional route — hiring human annotators to build supervised fine-tuning and
instruction-tuning sets — is described as costly and time-consuming, which limited such
datasets to a few key players. That changed: hundreds of high-quality synthetic
fine-tuning datasets have been developed, primarily using GPT-3.5 and GPT-4.

A second motivation is domain scarcity. Adapting LLMs to specific domains remains
difficult because high-quality domain data is scarce, and existing synthesis tools
struggle to extract reliable fine-tuning data from heterogeneous documents.

## Where it demonstrably works

The strongest evidence in this corpus is bounded by a condition:
[ReST-EM](../summaries/rest-em-beyond-human-data.md) shows self-training beats fine-tuning
on human data alone **on tasks where scalar feedback is available** — generate samples,
filter them by binary feedback, fine-tune, repeat. On MATH and APPS with PaLM-2 it scales
favourably with model size. The paper's own framing is that this *suggests* self-training
with feedback can reduce dependence on human data.

That condition matters. Where correctness cannot be checked, the filter that makes ReST-EM
work is not available.

## What is actually hard

Not generation — **diversity**. [Cosmopedia](../summaries/cosmopedia-synthetic-pretraining-data.md)
reports that most of the effort went into meticulous prompt engineering rather than
running generation across hundreds of GPUs, because at scale you must curate prompts that
minimize duplicate outputs or waste compute producing near-identical documents. Over 30
million prompts achieved under 1% duplicates.

Deduplication and inspection therefore belong to the same job; see
[data exploration and deduplication](../summaries/data-exploration-and-deduplication.md).

## The unresolved dispute

Worth recording rather than resolving: Cosmopedia notes that Phi models trained
predominantly on synthetic data surpassed larger models trained longer on web data, but
that critics argue they may simply be overfitting benchmarks, and some characterize
pretraining on synthetic data as "garbage in, garbage out". The Phi datasets themselves
were not released and their curation is not fully described, which is part of why the
argument persists.

Tooling: [Curator, Distilabel, Easy Dataset](../summaries/synthetic-data-tooling.md).
""",2)

# ---- papers ----
page(P/"Beyond Human Data.md","paper","Beyond Human Data: Scaling Self-Training for Problem-Solving with Language Models",
 "ReST-EM: EM-based self-training on binary-feedback-filtered model output, surpassing human-data fine-tuning",
 ["llm-finetuning","synthetic-data","self-training","paper"],["rest"],"""
# Beyond Human Data

Singh, Co-Reyes, Agarwal, and a large Google DeepMind author list, with Mila. 2024.

## Problem

Fine-tuning on human-generated data remains prevalent, but model performance is limited by
the **quantity and diversity of high-quality human data**, and acquiring it is a
significant bottleneck.

## Method — ReST-EM

A self-training method based on expectation-maximization, applied where scalar feedback
exists:

1. Generate samples from the model, filter with **binary feedback**.
2. Fine-tune on the filtered samples.
3. Repeat a few times.

Presented as a modification of Reinforced Self-Training (ReST, Gulcehre et al.), and shown
to be interpretable as expectation-maximization for reinforcement learning, drawing on
Dayan and Hinton (1997) and Peters and Schaal (2007).

## Results

On advanced **MATH** reasoning and **APPS** coding benchmarks with PaLM-2 models, ReST-EM
**scales favourably with model size and significantly surpasses fine-tuning only on human
data**. The paper reports substantial test-performance improvements on MATH and HumanEval.

## Claim as stated

> our findings suggest self-training with feedback can reduce dependence on
> human-generated data

Scoped to domains where correctness can be verified. The paper describes competition-level
mathematical problem-solving and code generation as two challenging, less explored domains
for comparing model-generated with human-generated data.

Summary: [rest-em-beyond-human-data](../summaries/rest-em-beyond-human-data.md).
""",2)

page(P/"Easy Dataset.md","paper","Easy Dataset: A Unified and Extensible Framework for Synthesizing LLM Fine-Tuning Data from Unstructured Documents",
 "GUI framework turning unstructured documents into fine-tuning QA pairs via chunking and persona-driven prompting",
 ["llm-finetuning","synthetic-data","datasets","paper"],["easy"],"""
# Easy Dataset

## Problem

LLMs perform well on general-purpose tasks, but adapting them to specific domains remains
challenging because **high-quality domain data is scarce**, and existing data synthesis
tools struggle to extract reliable fine-tuning data from heterogeneous documents.

## Approach

A unified framework for synthesizing fine-tuning data from unstructured documents through
an intuitive **graphical user interface**:

- Configurable **text extraction models and chunking strategies** turn raw documents into
  coherent text chunks.
- **Persona-driven prompting** generates diverse question-answer pairs using publicly
  available LLMs.
- A **human-in-the-loop visual interface** runs throughout, for reviewing and refining
  intermediate outputs to ensure data quality.

## Result

Experiments on a **financial question-answering task** report that fine-tuning on the
synthesized dataset **significantly improves domain-specific performance while preserving
general knowledge**.

Source code and an installable package are available, with the paper page noting over
9,000 GitHub stars.

Tooling summary: [synthetic-data-tooling](../summaries/synthetic-data-tooling.md).
""",2)
print("batch 3 pages written")
